[package]
name = "bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
merge = { path = "../merge" }
model = { path = "../model" }
parsing = { path = "../parsing" }
matching = { path = "../matching" }
utils = { path = "../utils" }
assert_cmd = "2.0.12"
predicates = "3.0.4"
clap = { version = "4.4.8", features = ["derive"] }

[[bin]]
name = "generic-merge"
path = "src/main.rs"
